name: Build and push Docker images

on:
  push:
    branches:
      - main

env:
  FRONTEND_IMAGE_NAME: fullstack-frontend
  BACKEND_IMAGE_NAME: fullstack-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest ./CMS-Frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest ./CMS-Backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env/BACKEND_IMAGE_NAME }}:latest
